version: '3'

services:
  reverse-proxy:
    image: traefik:v2.6
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  demo:
    build: demo
    container_name: "demo"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.demo.rule=Host(`demo.localhost`)"
    environment:
      - HSH_SERVER=http://server.localhost
    depends_on:
      - server

  server:
    build: .
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.server.rule=Host(`server.localhost`)"


