HEBREW_PREPOSITIONS = ["מ", "ל", "ב", "ו"]
LOCATION_PREPOSITIONS = HEBREW_PREPOSITIONS
DISEASE_PREPOSITIONS = HEBREW_PREPOSITIONS
MEDICATION_PREPOSITIONS = HEBREW_PREPOSITIONS
MEDICAL_TEST_PREPOSITIONS = HEBREW_PREPOSITIONS
